### ISSUE TITLE
Question about how to identify changepoints?

### ISSUE THREAD

**Issue by 8Jimmy** [Lucew/changepoynt#1]
After using detection algorithms in this toolbox, it seems that it will return a score sequence. My question is: How can we identify the changepoints using this score curve?

I appreciate it if you could spare time to answer my question. Thank you!!!!

**Comment by Lucew** [comment]
Hey @8Jimmy,

cool that you think about using our package. 😀 
You got that right, the methods compute a continuous score sequence the same length as the signal itself.

Unfortunately, there is not one simple way to answer your question. **Think about the methods of this package similar to an outlier score you get by anomaly detection methods**. Also, it is similar to classification score thresholding, which is the reason there are measures like the AUROC. We therefore keep thresholding separate from the package itself (which is intended to compute the scores).

The easiest way to detect change points is by using some threshold or peak identification tool (maybe after normalizing the scores). But there are other way more sophisticated methods of doing thresholding. Maybe you could look at popular anomaly detection libraries and how they approach the problem. There is [PyOD](https://github.com/yzhao062/pyod) for example which has its own small [section](https://github.com/yzhao062/pyod?tab=readme-ov-file#thresholding-outlier-scores) on the problem. They recommend to use a library like [PyThresh](https://github.com/KulikDM/pythresh).

We might think about implementing a simple way in the future, but it is currently not on the roadmap.

**Comment by Lucew** [comment]
Hey @8Jimmy,

is there anything more that I could help you with your problem?

Otherwise, I will close this issue in the next few days.
Feel free to get back to me or open another issue if you have any questions.

Cheers, Lucas
